### ISSUE TITLE
Push a new tag

### ISSUE THREAD

**Issue by tederer-man** [dancodes/megatools-docker#1]
The [latest tag in `dancodes/megatools`](https://hub.docker.com/r/dancodes/megatools/tags/) is two years old. https://github.com/megous/megatools has had many changes since then.

Mind pushing another with the latest megatools please 😺 ?

---

The regex in the current container doesn't support the latest Mega URLs, https://megatools.megous.com/man/megadl.html#_examples

```
$ megadl 'https://mega.nz/#F!HIlFDajT!HLiVvQQkSe1d0ogxZuaOJg'
WARNING: Skipping invalid Mega download link: https://mega.nz/#F!HIlFDajT!HLiVvQQkSe1d0ogxZuaOJg
```

---

Alternative, https://hub.docker.com/r/klutchell/megatools/

**Comment by dancodes** [comment]
Pushed. Thanks for letting me know!
